# -*- mode: ruby -*-
# vi: ft=ruby ts=2 et

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "vagrant-pwiz"

  config.vm.provision :shell, path: "install-docker.sh"
  config.vm.provision :shell, privileged: false, path: "docker-pwiz.sh"
    
end
